general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/gennux/Pictures/wallpapers/wall.jpg
    brightness = 0.4
}

input-field {
    monitor =
    size = 280, 52
    outline_thickness = 2
    dots_size = 0.26
    dots_spacing = 0.64
    dots_center = true
    outer_color = rgba(00c8ffaa)
    inner_color = rgba(05050fdd)
    font_color = rgb(cdd6f4)
    fade_on_empty = true
    placeholder_text = <span foreground="##cdd6f4"> Password</span>
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(cdd6f4ff)
    font_size = 72
    font_family = Geist Mono
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %B %d')"
    color = rgba(a6adc8ff)
    font_size = 20
    font_family = Inter
    position = 0, 80
    halign = center
    valign = center
}
